import {
  FaChartBar,
  FaShieldAlt,
  FaPercentage,
} from "react-icons/fa";

const iconMap = {
  "Total Transactions": (
    <FaChartBar className="text-cyan-400 text-3xl" />
  ),
  "Fraud Detected": (
    <FaShieldAlt className="text-red-400 text-3xl" />
  ),
  "Fraud Percentage": (
    <FaPercentage className="text-yellow-400 text-3xl" />
  ),
};

const AnalyticsCard = ({
  title,
  value,
  color,
}) => {
  return (
    <div
      className="
      bg-slate-900
      border
      border-slate-800
      rounded-3xl
      p-6
      shadow-xl
      hover:border-cyan-500
      hover:-translate-y-1
      transition-all
      duration-300
      "
    >
      {/* Top */}

      <div className="flex items-center justify-between">

        <div>

          <p className="text-gray-400 text-sm uppercase tracking-wider">

            {title}

          </p>

          <h2
            className={`text-4xl font-extrabold mt-4 ${color}`}
          >
            {value}
          </h2>

        </div>

        <div
          className="
          w-14
          h-14
          rounded-2xl
          bg-slate-800
          flex
          items-center
          justify-center
          "
        >
          {iconMap[title]}
        </div>

      </div>

      {/* Bottom */}

      <div className="mt-6 border-t border-slate-800 pt-4">

        <p className="text-gray-500 text-sm">

          Live analytics generated by
          CryptoGuard AI

        </p>

      </div>

    </div>
  );
};

export default AnalyticsCard;