import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";

const FraudHistogram = ({ data }) => {

  if (!data || data.length === 0) {

    return (

      <div className="bg-slate-900 border border-slate-800 rounded-3xl shadow-xl">

        <div className="p-6 border-b border-slate-800">

          <h2 className="text-3xl font-bold text-white">
            Fraud Score Distribution
          </h2>

          <p className="text-gray-400 mt-2">
            Upload a cryptocurrency transaction dataset to visualize
            fraud score distribution.
          </p>

        </div>

        <div className="h-[400px] flex items-center justify-center text-gray-500">

          No data available

        </div>

      </div>

    );

  }

  return (

    <div className="bg-slate-900 border border-slate-800 rounded-3xl shadow-xl">

      {/* Header */}

      <div className="p-6 border-b border-slate-800">

        <h2 className="text-3xl font-bold text-white">
          Fraud Score Distribution
        </h2>

        <p className="text-gray-400 mt-2">
          Distribution of fraud scores generated by the AI model.
        </p>

      </div>

      {/* Chart */}

      <div className="p-6">

        <ResponsiveContainer
          width="100%"
          height={400}
        >

          <BarChart
            data={data}
            margin={{
              top: 20,
              right: 20,
              left: 10,
              bottom: 10,
            }}
          >

            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#334155"
            />

            <XAxis
              dataKey="range"
              stroke="#94a3b8"
            />

            <YAxis
              stroke="#94a3b8"
            />

            <Tooltip />

            <Bar
              dataKey="count"
              fill="#06b6d4"
              radius={[8, 8, 0, 0]}
            />

          </BarChart>

        </ResponsiveContainer>

      </div>

    </div>

  );

};

export default FraudHistogram;