import { FaRobot, FaCheckCircle, FaExclamationTriangle } from "react-icons/fa";

const AIInsights = ({
  totalTransactions = 0,
  fraudDetected = 0,
  fraudPercentage = 0,
}) => {
  const risk =
    fraudPercentage > 10
      ? "High"
      : fraudPercentage > 3
      ? "Medium"
      : "Low";

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl mb-8">

      <div className="flex items-center gap-3 mb-6">

        <div className="w-12 h-12 rounded-xl bg-cyan-500/20 flex items-center justify-center">
          <FaRobot className="text-cyan-400 text-xl" />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">
            AI Insights
          </h2>

          <p className="text-gray-400 text-sm">
            Automatic analysis generated by CryptoGuard AI
          </p>
        </div>

      </div>

      <div className="space-y-4">

        <div className="flex items-center gap-3">
          <FaCheckCircle className="text-green-400" />
          <span>Total Transactions Analysed:</span>
          <span className="font-bold text-cyan-400">
            {totalTransactions}
          </span>
        </div>

        <div className="flex items-center gap-3">
          <FaCheckCircle className="text-green-400" />
          <span>Fraud Detected:</span>
          <span className="font-bold text-red-400">
            {fraudDetected}
          </span>
        </div>

        <div className="flex items-center gap-3">
          <FaExclamationTriangle className="text-yellow-400" />
          <span>Risk Level:</span>

          <span
            className={`font-bold ${
              risk === "High"
                ? "text-red-400"
                : risk === "Medium"
                ? "text-yellow-400"
                : "text-green-400"
            }`}
          >
            {risk}
          </span>
        </div>

        <div className="mt-6 bg-slate-800 rounded-2xl p-4">

          <h3 className="font-semibold text-cyan-400 mb-2">
            Recommendation
          </h3>

          <p className="text-gray-300 leading-7">

            {totalTransactions === 0
              ? "Upload a cryptocurrency transaction dataset to begin AI-powered fraud analysis."
              : fraudPercentage > 10
              ? "High fraud activity detected. Investigate flagged transactions immediately."
              : fraudPercentage > 3
              ? "Moderate fraud activity detected. Review suspicious transactions carefully."
              : "Transaction activity appears normal. Continue monitoring incoming transactions."}

          </p>

        </div>

      </div>

    </div>
  );
};

export default AIInsights;